### ISSUE TITLE
Some Processing libraries not included with core1.1.jar

### ISSUE THREAD

**Issue by angusforbes** [n8han/spde#1]
Hi, this is a great project!!

In porting one of my Processing sketches to spde I found that none of the Processing libraries are included with spde. That is, beside the core lib, which means opengl and other libs need to be copied in to the sbt project manually. Is there any reason that the full functionality of Processing isn't ported over to spde? I was able to add them by placing them in a lib directory that I created.

This is probably a general sbt question, but when I do add the processing opengl.jar and jogl native libs to the lib/ directory the native libs aren't found by sbt. That is, how do I execute a 
    -Djava.library.path=...
from sbt?

Putting my jogl/gluegen .jnilibs in the root project directory works as well and I can compile. However when I run this basic example I get this error:

```
[info] Invalid memory access of location 0x0 rip=0x7fff83aa8977
[info] 
[info] == run ==
[error] Error running run: Nonzero exit code returned from runner: 139
```

Here's the code from the glob.scala file (the sample OpenGL is from the Processing website):

```
import processing.core._
import spde.core._
import PConstants._
import PApplet._
object `graftRunner` {
   def main(args: Array[String]) { PApplet.main(Array(classOf[`graft`].getName)) }
}
class `graft` extends ProxiedApplet {
   lazy val px = new DrawProxy(this) {
     import processing.opengl._; // Sketch.spde: 1
       // Sketch.spde: 2
     var a = 0f // Sketch.spde: 3
       // Sketch.spde: 4
     size(800, 600, OPENGL); // Sketch.spde: 5
     fill(0, 153); // Sketch.spde: 6
     noStroke(); // Sketch.spde: 7
     // Sketch.spde: 8
     def draw() { // Sketch.spde: 9
       background(255); // Sketch.spde: 10
       translate(width / 2, height / 2); // Sketch.spde: 11
       rotateX(a); // Sketch.spde: 12
       rotateY(a * 2); // Sketch.spde: 13
       rect(-200, -200, 400, 400); // Sketch.spde: 14
       rotateX(PI / 2); // Sketch.spde: 15
       rect(-200, -200, 400, 400); // Sketch.spde: 16
       a += 0.01; // Sketch.spde: 17
     } // Sketch.spde: 18
   }
```

Anyhow, I'll play around with it. If anyone has already figured this out let me know! Thanks, Angus

**Comment by angusforbes** [comment]
Oops, I've just realized that there is a project called spde-examples with an opengl example...

Copying the Matrix.spde code into my sketch works great... The issue was that you need to override the setup method explicitly when using OPENGL rendering.

Ok, the project Matrix works great on OSX x86_64!

**Comment by n8han** [comment]
That's right. :) The jars that are put into lib_managed depend on the project definition. And if you ever need to add custom jars to the project, you can create a "lib" directory and everything in it will go onto the project classpath by default.

**Comment by CodeCombiner** [comment]
Sorry, i didn't catch. In wich directiry the "lib" directory must be created?
