### ISSUE TITLE
Upgrade SPDE to Use the Latest Stable Release of Scala

### ISSUE THREAD

**Issue by jedishrfu** [n8han/spde#3]
Currently the SPDE tool uses 2.7.4 Scala, I naively copied in the latest scala libraries into the lib thinking the tool was loosely coupled to scala but got an error wrt to a missing scala iterable class at startup.

Can the tool be upgraded to the latest scala or better yet be configured to look for the SCALA_HOME environment param and go from there?

**Comment by hawkw** [comment]
I know this is a really old issue, but I'd really love to see SPDE updated to a later Scala version as well. I'm thinking about forking SPDE and updating it to work with the newest Scala and sbt versions, but I'm not entirely sure what would be necessary to update SPDE and the plugin, as I'm not too familiar with how it works internally. I'd really appreciate some pointers from the original authors on that.

**Comment by jedishrfu** [comment]
Me too I'm not an original author though.

Perhaps you can contact the Processing authors about how to write a plugin
for Processing that provides a Scala mode. Some people have done it for
Javascript and for Python using the java-based compilers/interpreters for
these languages.

Casey Reas (Processing co-author) pointed me to these two sources as
examples:

https://github.com/fjenett/coffeescript-mode-processing
https://github.com/fjenett/javascript-mode-processing

but I ran out of time to investigate further.

Perhaps they will help you get it working.

I know the original SPDE is based on Processing 1.x and they did a lot of
changes to get to the latest versions of processing. I think you'll need
Eclipse IDE to work with everything not sure how they build Processing now
ie via maven or ant.

**Comment by jedishrfu** [comment]
Thanks, that worked. I didn't realize you could do that on Github. Some
sites have a time limit on posts and I had forgotten my password.

Thanks again,
